name: Deploy Preview to Vercel on main push

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write
  id-token: write

jobs:
  vercel-deploy:
    name: Deploy to Vercel Preview
    runs-on: ubuntu-latest

    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Vercel CLI and PNPM
        run: |
          npm install --global vercel@latest pnpm

      - name: Pull Vercel environment (preview)
        run: |
          vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Install dependencies (pnpm)
        run: |
          pnpm install

      - name: Build project using Vercel
        run: |
          vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        id: deploy
        run: |
          PREVIEW_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | tail -n 1)
          echo "preview_url=$PREVIEW_URL" >> $GITHUB_OUTPUT

      - name: Clean up .vercel folder
        run: rm -rf .vercel

      - name: Output Preview URL
        run: |
          echo "✅ Preview URL: ${{ steps.deploy.outputs.preview_url }}"
